%YAML:1.0
# data
# dataset_dir: /media/mzins/DATA1/Kitti/data_odometry_gray/dataset/sequences/00
dataset_dir: /media/mzins/DATA1/7-Scenes/chess/seq-01
# dataset_dir: /media/mzins/DATA1/7-Scenes/office/seq-01
# dataset_dir: /media/mzins/DATA1/7-Scenes/redkitchen/seq-01

# mode: stereo
mode: depth

num_features: 200
num_features_init: 100
num_features_tracking: 50
num_features_tracking_bad: 20
min_num_points_init_map: 10
num_features_needed_for_keyframe: 80

# viewer_camera_size: 1.0
viewer_camera_size: 0.2